// DPO CARD — Days Payable Outstanding, the average time the club takes to
// pay a bill (Marcello's spec, item 5 — the payables mirror of DsoCard,
// added 2026-08-04, fix-28-treasury-align, mandate extension #1).
//
// FORMULA — the book-value trailing-average method:
//
//   DPO = Payables (today's open AP book, ap_aging_v2) / Trailing-12-month
//         COGS x 365
//
// TRAILING REFERENCE — v_balance_sheet_monthly's L_AP line ("Trade
// payables"), NOT v_working_capital_monthly.payables. Verified live
// 2026-08-04: v_working_capital_monthly.payables runs SAR 630k-1.1M across
// the last 14 months — 15-25x LARGER than ap_aging_v2's today figure
// (SAR 41,817, post migration-074 fix) and not even close to the balance
// sheet's own L_AP "Trade payables" control line for the same months
// (SAR 58k-456k) — it is evidently a different, broader working-capital
// construct, not the same population ap_aging_v2 approximates. Diffing
// Current DPO (ap_aging_v2, narrow open-bill snapshot) against that figure
// would have reproduced, inside this brand-new card, the exact "two truths"
// class of bug this whole fix pass exists to eliminate (see migration 074).
// L_AP is the balance-sheet's own trade-payables control account — same
// order of magnitude as ap_aging_v2 today (SAR 57,762 at 2026-06-30 vs
// SAR 41,817 today, a plausible ~2-month drift) and always positive across
// the trailing 12 months (checked; the deeper history has adjustment-era
// swings from years back that never enter this trailing window). Method
// difference from Current DPO (open-bill snapshot vs balance-sheet control
// account) is disclosed on screen, not hidden — same house discipline as
// DsoCard's realized-vs-book-value disclosure.
//
// COGS (not full opex) is the denominator, mirroring DSO's choice of Revenue
// (the top-line driver) rather than net result — payables are predominantly
// generated by cost postings (vendor bills), so trailing COGS is the more
// meaningful "purchases" proxy than the full P&L.
import { useMemo } from "react";
import { Card } from "@/components/ui/card";
import { Tooltip, TooltipContent, TooltipTrigger } from "@/components/ui/tooltip";
import { TrendingUp, TrendingDown, Minus, Info, Wallet2 } from "lucide-react";
import { cn } from "@/lib/utils";
import { useApAging, useBalanceSheet } from "@/data/statementsLive";
import { useBasisRows, aggregatePL, lastCompleteFromBasis } from "@/data/alignment";
import { monthKey, shiftMonthKey, monthKeyLabel } from "@/data/liveData";
import { fmtDeltaPct, pctChange } from "@/lib/format";
import { DataSourceBadge } from "@/components/dashboard/DataSourceBadge";

const n = (v: number | null | undefined): number => v ?? 0;

const trailingCogs = (basisData: ReturnType<typeof useBasisRows>["data"], endKey: string): number => {
  const win = { startKey: shiftMonthKey(endKey, -11), endKey };
  return Math.abs(aggregatePL(basisData?.rows, "STRICT", win).cogs);
};

export const DpoCard = ({ className }: { className?: string }) => {
  const { data: basis, isLoading: basisLoading } = useBasisRows();
  const ap = useApAging();
  const { data: bs, isLoading: bsLoading } = useBalanceSheet();

  const apTotal = useMemo(
    () => (ap.data?.available ? ap.data.rows.reduce((s, r) => s + n(r.residual_amount), 0) : null),
    [ap.data],
  );

  const lastComplete = useMemo(() => lastCompleteFromBasis(basis?.rows), [basis]);

  const currentDpo = useMemo(() => {
    if (apTotal === null || !lastComplete) return null;
    const cogs = trailingCogs(basis, lastComplete);
    if (cogs <= 0) return null;
    return (apTotal / cogs) * 365;
  }, [apTotal, basis, lastComplete]);

  // L_AP ("Trade payables") monthly control-account balance — see header for
  // why this replaces v_working_capital_monthly.payables.
  const lapByMonth = useMemo(() => {
    if (!bs?.available) return null;
    const m = new Map<string, number>();
    for (const r of bs.rows) {
      if (r.line_code === "L_AP") m.set(monthKey(r.month), n(r.amount));
    }
    return m;
  }, [bs]);

  const history = useMemo(() => {
    if (!lapByMonth || !lastComplete) return { points: [] as { key: string; dpo: number }[], monthsAvailable: 0, excludedNegative: 0 };
    const sorted = [...lapByMonth.entries()]
      .map(([key, payables]) => ({ key, payables }))
      .filter((r) => r.key <= lastComplete)
      .sort((a, b) => a.key.localeCompare(b.key));
    const last12 = sorted.slice(-12);
    // Defensive guard — L_AP is positive across the trailing 12 months
    // observed live, but the deeper history (pre-2025) carries
    // adjustment-era negative swings; exclude rather than average in a
    // meaningless negative "days of payables" should the window ever reach
    // back that far.
    let excludedNegative = 0;
    const points = last12
      .map((m) => {
        if (m.payables < 0) { excludedNegative += 1; return null; }
        const cogs = trailingCogs(basis, m.key);
        return cogs > 0 ? { key: m.key, dpo: (m.payables / cogs) * 365 } : null;
      })
      .filter((p): p is { key: string; dpo: number } => p !== null);
    return { points, monthsAvailable: points.length, excludedNegative };
  }, [lapByMonth, basis, lastComplete]);

  const avgDpo = history.points.length > 0
    ? history.points.reduce((s, p) => s + p.dpo, 0) / history.points.length
    : null;

  const isLoading = basisLoading || bsLoading || (ap.isLoading && !ap.data);
  const deltaAbs = currentDpo !== null && avgDpo !== null ? currentDpo - avgDpo : null;
  const deltaPct = currentDpo !== null && avgDpo !== null ? pctChange(currentDpo, avgDpo) : null;
  const tone = deltaAbs === null ? "na" : Math.abs(deltaAbs) < 0.5 ? "flat" : deltaAbs > 0 ? "up" : "down";
  // For DPO, "up" (paying LATER, holding cash longer — good treasurer
  // behaviour per Marcello's own principle) still uses the mechanical
  // up=azure/down=red rule, same plain direction-of-change signal as
  // everywhere else, not a value judgement baked into the color.
  const TONE_TEXT: Record<string, string> = { up: "text-success", down: "text-destructive", flat: "text-muted-foreground", na: "text-muted-foreground" };
  const Icon = tone === "up" ? TrendingUp : tone === "down" ? TrendingDown : Minus;

  return (
    <Card className={cn("p-6 shadow-sm animate-fade-in", className)}>
      <div className="flex items-center gap-3 mb-1 flex-wrap">
        <h3 className="text-xl font-heading tracking-wide inline-flex items-center gap-2">
          <Wallet2 className="h-5 w-5 text-gold" /> DPO — DAYS PAYABLE OUTSTANDING
        </h3>
        <DataSourceBadge source="live" sourceLabel="Live data from Supabase (ap_aging_v2 + v_pnl_basis + v_balance_sheet_monthly)" />
      </div>

      <p className="text-sm text-muted-foreground mb-4 inline-flex items-start gap-1.5">
        <span>
          The average time the club takes to pay a bill, in days — stai pagando prima o dopo rispetto agli ultimi
          12 mesi. Current = today's open payables ÷ trailing-12-month cost of goods sold × 365.
        </span>
        <Tooltip>
          <TooltipTrigger asChild><Info className="h-3.5 w-3.5 mt-0.5 text-gold/80 cursor-help shrink-0" /></TooltipTrigger>
          <TooltipContent side="top" className="max-w-sm text-xs space-y-1.5">
            <p>
              <strong>Current DPO</strong>: today's live open-bills snapshot (ap_aging_v2) divided by trailing-12-month
              COGS (the purchases proxy), annualised ×365.
            </p>
            <p>
              <strong>Last-12m average</strong>: each trailing month's own DPO, from the balance sheet's Trade
              Payables control line (v_balance_sheet_monthly, L_AP) ÷ its own trailing-12m COGS — a different,
              broader source than the live open-bill snapshot, deliberately NOT v_working_capital_monthly (checked:
              that figure runs 15-25x larger than ap_aging_v2, a different population entirely).
            </p>
            <p>
              A higher DPO means paying vendors later relative to purchase volume — holding cash longer, the
              treasurer's own definition of good working-capital management, not a red flag by itself.
            </p>
          </TooltipContent>
        </Tooltip>
      </p>

      {isLoading ? (
        <div className="h-28 rounded-lg bg-muted animate-pulse" />
      ) : currentDpo === null ? (
        <p className="text-sm text-muted-foreground">
          Not enough data yet to compute DPO (needs a posted-cost month for trailing COGS, and a live AP aging
          figure).
        </p>
      ) : (
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-6 items-center">
          <div className="flex flex-col items-center sm:items-start">
            <span className="text-xs uppercase tracking-wider text-muted-foreground">Current DPO</span>
            <span className="font-heading text-4xl md:text-5xl tracking-tight tabular-nums">
              {currentDpo.toFixed(0)} <span className="text-lg text-muted-foreground font-sans">days</span>
            </span>
            <span className="text-xs text-muted-foreground mt-1">
              trailing 12m COGS to {lastComplete ? monthKeyLabel(lastComplete) : "—"}
            </span>
          </div>

          <div className="flex flex-col items-center sm:items-start border-t sm:border-t-0 sm:border-l border-border/60 pt-4 sm:pt-0 sm:pl-6">
            <span className="text-xs uppercase tracking-wider text-muted-foreground inline-flex items-center gap-1">
              Last-12-months average {history.monthsAvailable < 12 - history.excludedNegative && (
                <span className="text-amber-400">(only {history.monthsAvailable} mo. available)</span>
              )}
            </span>
            {avgDpo === null ? (
              <span className="text-sm text-muted-foreground mt-1">Not enough history yet.</span>
            ) : (
              <>
                <span className="font-heading text-3xl md:text-4xl tracking-tight tabular-nums">
                  {avgDpo.toFixed(0)} <span className="text-base text-muted-foreground font-sans">days</span>
                </span>
                <span className={cn("inline-flex items-center gap-1 text-sm font-semibold mt-1", TONE_TEXT[tone])}>
                  <Icon className="h-3.5 w-3.5" aria-hidden />
                  {deltaAbs !== null ? `${deltaAbs > 0 ? "+" : ""}${deltaAbs.toFixed(0)} days` : "—"}
                  {deltaPct !== null && <span> · {fmtDeltaPct(deltaPct)}</span>}
                  <span className="font-normal text-muted-foreground">vs average</span>
                </span>
                <span className="text-[11px] text-muted-foreground mt-1">
                  balance-sheet trade-payables basis (not the ap_aging_v2 snapshot Current DPO uses)
                </span>
              </>
            )}
          </div>
        </div>
      )}
    </Card>
  );
};
